# Generated by Django 2.0.1 on 2018-01-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.TextField(max_length=300, null=True)),
                ('gospel', models.CharField(choices=[('Mt', 'Mateus'), ('Lc', 'Lucas'), ('Mc', 'Marcos'), ('Jo', 'João'), ('At', 'Atos dos apóstolos'), ('Rom', 'Romanos'), ('I Cor', 'Primeira epístola Coríntios'), ('II Cor', 'Segunda epístolas Coríntios'), ('Gal', 'Gálatas'), ('Ef', 'Efésios'), ('Flp', 'Filipenses'), ('Col', 'Colossenses'), ('I Tes', 'Primeira epístola Tessalonicenses'), ('II Tes', 'Segunda epístola Tessalonicenses'), ('I Tim', 'Primeira epístola a Timóteo'), ('II Tim', 'Primeira epístola a Timóteo')], max_length=8)),
                ('chapter_number', models.IntegerField(default=0, null=True)),
                ('verse_begin', models.IntegerField(default=1, null=True)),
                ('verse_end', models.IntegerField(default=1, null=True)),
            ],
        ),
    ]
